### ISSUE TITLE
Runs for me

### ISSUE THREAD

**Issue by coryhouse** [RwemaALC4/pluralsight-js-dev-env#1]
Make sure you're running at least Node 6. Run this on the command line to check your version: `node -v` 

Your code runs for me. I did this:
`npm install`
`node buildScripts/srcServer.js`

If that doesn't work, please post back with your operating system, Node version, and any output you're getting on the command line.

**Comment by RwemaALC4** [comment]
I have `node v10.15.2`  
I on `debian 10 (Buster)`  
There is no output on the terminal after running `node builScripts/srcServer.js` command.

**Comment by coryhouse** [comment]
Sorry, I don't have a Debian machine so I can't reproduce. Does the final course exercise run for you? Click on exercise files on the course page.

**Comment by RwemaALC4** [comment]
This is what I am getting when I access exercise files.  
![Screenshot from 2019-07-16 16-59-14](https://user-images.githubusercontent.com/52883196/61305449-2451bb00-a7eb-11e9-98a6-fdada85f5b1b.png)

**Comment by coryhouse** [comment]
Ah yes, didn't realize they were hiding the button from people at the moment. Here ya go: https://www.dropbox.com/s/2w0rn5rezfm7rpq/demos.zip?dl=0

**Comment by RwemaALC4** [comment]
Can't run the `node buildScripts/srcServer.js`. Don't know what to do.  
![Screenshot from 2019-07-16 17-50-28](https://user-images.githubusercontent.com/52883196/61309330-46027080-a7f2-11e9-9a44-b53763d7b1fa.png)

**Comment by coryhouse** [comment]
Run this:

`npm start`

**Comment by RwemaALC4** [comment]
I am getting this error

![Screenshot from 2019-07-17 09-46-34](https://user-images.githubusercontent.com/52883196/61357118-01211d00-a878-11e9-98a5-4d65f9b57bde.png)

**Comment by RwemaALC4** [comment]
well, when I enter `localhost:3000` in the browser am able to access the `index.html` page.

**Comment by coryhouse** [comment]
So you got it working? Based on the error you got above, you needed to run `npm install` to install dependencies. Then run `npm start`.
